// <auto-generated />
using DugnadApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DugnadApp.Migrations
{
    [DbContext(typeof(DugnadDbContext))]
    [Migration("20260608164508_OpprettTabeller")]
    partial class OpprettTabeller
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DugnadApp.Models.Beboer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seksjonsnr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Beboere");
                });

            modelBuilder.Entity("DugnadApp.Models.Leilighet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Leilighetsnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seksjonsnr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Leilighet");
                });
#pragma warning restore 612, 618
        }
    }
}
