// <auto-generated />
using System;
using DugnadApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DugnadApp.Migrations
{
    [DbContext(typeof(DugnadDbContext))]
    partial class DugnadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DugnadApp.Models.Beboer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ErAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seksjonsnr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Beboere");
                });

            modelBuilder.Entity("DugnadApp.Models.Deltakelse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BeboerId")
                        .HasColumnType("integer");

                    b.Property<string>("Beskrivelse")
                        .HasColumnType("text");

                    b.Property<int>("DugnadId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistrertDato")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Timer")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BeboerId");

                    b.HasIndex("DugnadId");

                    b.ToTable("Deltakelser");
                });

            modelBuilder.Entity("DugnadApp.Models.Dugnad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("boolean");

                    b.Property<bool>("KreverBeskrivelse")
                        .HasColumnType("boolean");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Dugnader");
                });

            modelBuilder.Entity("DugnadApp.Models.Leilighet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Leilighetsnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Seksjonsnr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Leiligheter");
                });

            modelBuilder.Entity("DugnadApp.Models.LoginCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Brukt")
                        .HasColumnType("boolean");

                    b.Property<string>("Epost")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Opprettet")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Utloper")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("LoginCoder");
                });

            modelBuilder.Entity("DugnadApp.Models.Deltakelse", b =>
                {
                    b.HasOne("DugnadApp.Models.Beboer", "Beboer")
                        .WithMany()
                        .HasForeignKey("BeboerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DugnadApp.Models.Dugnad", "Dugnad")
                        .WithMany()
                        .HasForeignKey("DugnadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beboer");

                    b.Navigation("Dugnad");
                });
#pragma warning restore 612, 618
        }
    }
}
